# Generated by Django 4.2.17 on 2025-01-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center_app', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
