# Generated by Django 4.2.17 on 2025-01-08 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_center_app', '0005_order_quantity_remove_order_service_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
