# Generated by Django 4.2.17 on 2025-01-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_center_app', '0007_client_name_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
