# Generated by Django 4.2.17 on 2025-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center_app', '0008_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
